[package]
name = "random-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.53"
bytemuck = "1.9.1"
getrandom = "0.2.6"
wasmbox = {path="../../wasmbox"}
